### ISSUE TITLE
[漏洞报告]include攻击

### ISSUE THREAD

**Issue by Ruanxingzhi** [zjhzxhz/voj#14]
voj有一个小毛病：

交上这个代码会有点小问题：
```cpp
#include "/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/voj.properties"
```

这个小问题如下：
![233](http://i1.piimg.com/4851/a67bf91bf261b000.png)

然后mysql密码就被爆出来啦~\(≧▽≦)/~

**解决方案：**
``chmod /var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/voj.properties 755``

**Comment by riteme** [comment]
HUSTOJ已经被这样炸过一次了......

**Comment by zjhzxhz** [comment]
哇哦~~ Cool~~
非常感谢~!!

可是这个问题怎么解决呢?

**Comment by Ruanxingzhi** [comment]
Linux下，把voj.properties权限设置成755即可。
```
chmod /var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/voj.properties 755
```

Windows不知如何解决。

**Comment by zjhzxhz** [comment]
可是如果通过修改权限的话 对于用户来说在部署时就多了一个步骤.
有没有更好的解决方案呢~
容我也想想看.

**Comment by riteme** [comment]
Windows好像有点搞不定，Docker不支持Windows......

**Comment by Ruanxingzhi** [comment]
一个奇技淫巧：
在配置文件最开始加``/*``，最后加``*/``，然后整个include不会有提示。

**Comment by riteme** [comment]
有个不太清真的方法
由于只有C/C++使用include
而`#`正好是C/C++的预处理符号
因此可以在配置文件首尾加上这样的东西：

```c++
#if false

// Settings goes here.

#endif
```

然后编译器在编译时就会跳过这一段。

**Comment by virusdefender** [comment]
其实最根本的还是配置权限和做chroot

**Comment by Ruanxingzhi** [comment]
@virusdefender 在这里也看到你了2333333

**Comment by mcfx0** [comment]
Pascal 也有include的。。{$I xxx}

**Comment by lizy14** [comment]
@riteme

'''
#define false 1
#include </evil>
#define false 0
'''

**Comment by hzxie** [comment]
@lizy14 
对哦～！那怎么办 - -|||

**Comment by ryanlee2014** [comment]
@lizy14 
你这个方法我觉得可以这么防范
```cpp
#undef false
#if false
// .......
#end if
```
