### ISSUE TITLE
判题机是阿里云吗

### ISSUE THREAD

**Issue by zhblue** [zjhzxhz/voj#16]
不会放图，不过下面这些文字应该足以说明了。
```
[zjhzxhz@XieHaozhe-InternalServer ~]$

```

**Comment by zjhzxhz** [comment]
嗯~ 万恶的`system`.
有什么好的解决方案吗?

我觉得你能获取到这些信息的关键还是因为你使用了公钥登录.
如果我禁用了公钥登录 你也就无法获取这些信息了, right?

**Comment by zhblue** [comment]
ptrace或docker
欢迎用hustoj做判题端

**Comment by zjhzxhz** [comment]
@zhblue 
好的~ 真的非常感谢~~

可是HUSTOJ没法做到跨平台吧~
另一方面, 自己解决这些问题真的有很大的收获~ 所以也想自己解决试试看.

**Comment by zhblue** [comment]
可以win上用现在的，Linux魔改一个hustoj的。

**Comment by zjhzxhz** [comment]
@zhblue 
好的 感谢~~
我晚些时候研究看看.
